'use strict';

const G = {
  REGISTER_START: new Date('2026-03-06T00:00:00'),
  HUNT_START:     new Date('2026-03-07T12:00:00'),
  HUNT_END:       new Date('2026-03-11T23:59:00'),

  IG_POST_A:  'https://www.instagram.com/locali_studentlife?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
  IG_POST_B:  'https://www.instagram.com/locali_studentlife?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
  IG_PROFILE: 'https://www.instagram.com/locali_studentlife?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',

  KAKTUS_CODE: 'KAKTUS52',
  INDIE_CODE:  'INDIE2026',

  FINAL_NAME:    'Indieflavours Bielefeld',
  FINAL_ADDRESS: 'Mauerstraße 52, 33602 Bielefeld',
  FINAL_MAP:     'https://maps.google.com/?q=Indieflavours+Bielefeld+Mauerstrase+52',
  KAKTUS_MAP:    'https://share.google/J2fruJExUS1heH3Sg',

  STOPS: {
    A: [
      { id:'a1', number:1, sticker_code:'KBR-7',
        gmaps:'https://maps.google.com/?q=52.0242845,8.5389817', fragment:'N52°01',
        hint:{ en:'A coordinate fragment. Copy it exactly — every character matters.', de:'Ein Koordinatenfragment. Genau abschreiben — jedes Zeichen zählt.' },
        next_clue:{ en:'From here, find the building where the city makes its decisions. On your way, look for the letters "16T" on something old.', de:'Von hier aus: finde das Gebäude, in dem die Stadt ihre Entscheidungen trifft. Achte unterwegs auf die Buchstaben „16T" auf etwas Altem.' },
        next_url:'stops/stop-a2.html' },
      { id:'a2', number:2, sticker_code:'RAT-4',
        gmaps:'https://maps.google.com/?q=52.0213634,8.5350583', fragment:'E008°31',
        hint:{ en:'Another coordinate fragment. Copy it exactly.', de:'Noch ein Koordinatenfragment. Genau abschreiben.' },
        next_clue:{ en:'Head north to the large open square in the heart of Bielefeld. Find the spiral fountain.', de:'Geh nach Norden zum großen offenen Platz im Herzen Bielefelds. Finde den Spiralbrunnen.' },
        next_url:'stops/stop-a3.html' },
      { id:'a3', number:3, sticker_code:'JPN-9',
        gmaps:'https://maps.google.com/?q=52.0255450,8.5311943', fragment:'#4A-F2',
        hint:{ en:'An identifier code. The letters are initials of something important.', de:'Ein Identifikationscode. Die Buchstaben sind Initialen von etwas Wichtigem.' },
        next_clue:null, next_url:null },
    ],
    B: [
      { id:'b1', number:1, sticker_code:'PMR-2',
        gmaps:'https://maps.google.com/?q=52.0184171,8.5296325', fragment:'BF-3360',
        hint:{ en:'A city and postcode fragment. Copy it exactly.', de:'Ein Stadt- und Postleitzahlfragment. Genau abschreiben.' },
        next_clue:{ en:'From here, walk into the old town (Altstadt). Find a telephone booth that reminds you of London.', de:'Von hier aus: geh in die Altstadt. Finde eine Telefonzelle, die dich an London erinnert.' },
        next_url:'stops/stop-b2.html' },
      { id:'b2', number:2, sticker_code:'ALT-6',
        gmaps:'https://maps.google.com/?q=52.020826,8.531890', fragment:'MW-52-X',
        hint:{ en:'A street reference code. Copy every character.', de:'Ein Straßenreferenzcode. Jedes Zeichen abschreiben.' },
        next_clue:{ en:'Walk to Jahnplatz. Find the tower that holds a machine that must always run to be right.', de:'Geh zum Jahnplatz. Finde den Turm, der eine Maschine beherbergt, die immer laufen muss, um richtig zu sein.' },
        next_url:'stops/stop-b3.html' },
      { id:'b3', number:3, sticker_code:'JTW-3',
        gmaps:'https://maps.google.com/?q=52.0230201,8.5331087', fragment:'IDF-26',
        hint:{ en:'A name and year code. The letters are initials.', de:'Ein Name- und Jahrescode. Die Buchstaben sind Initialen.' },
        next_clue:null, next_url:null },
    ],
  },

  DECODER: {
    ANSWER_A: 'N52°01E008°31#4A-F2',
    ANSWER_B:  'BF-3360MW-52-XIDF-26',
    STEPS: [
      { delay:0,
        label:{ en:'The restaurant name', de:'Der Restaurantname' },
        html:'#4A-F2 + IDF-26 → initials <strong>IDF</strong> = <strong>InDieFlavours</strong>. City code BF = <strong>Bielefeld</strong>.' },
      { delay:1400,
        label:{ en:'The street', de:'Die Straße' },
        html:'MW in MW-52-X → <strong>Mauer</strong>straße.' },
      { delay:2800,
        label:{ en:'The house number', de:'Die Hausnummer' },
        html:'N52°01 → digits before ° = <strong>52</strong>.' },
      { delay:4200,
        label:{ en:'The postal code', de:'Die Postleitzahl' },
        html:'BF-<strong>3360</strong> + last digit of #4A-F<strong>2</strong> → <strong>33602</strong>.' },
      { delay:5600,
        label:{ en:'The full address — go here', de:'Die vollständige Adresse — geht dorthin' },
        html:'<span style="font-family:var(--syne);font-size:1.1rem;font-weight:800;letter-spacing:.03em;color:var(--gold);">Indieflavours Bielefeld<br>Mauerstraße 52, 33602 Bielefeld</span>' },
    ],
  },

  FORMS: {
    TEAM: {
      ACTION:    'https://docs.google.com/forms/d/e/1FAIpQLSf0eop7Fl2LL82N6VG9f-4ZCXM5Un3zBir7cyC2FsVnp9OKBA/formResponse',
      PLAYER:    'entry.415857790', PARTNER:'entry.639059933',
      TEAMNAME:  'entry.419392051', ROLE:'entry.241583206', TIMESTAMP:'entry.18026000',
    },
    KAKTUS: {
      ACTION:    'https://docs.google.com/forms/d/e/1FAIpQLSdMqqiP5mVW1kyPWEomCwBF_8a397JpILyRWiFCJZ6AdpuozQ/formResponse',
      PLAYER:    'entry.2061720601', TIMESTAMP:'entry.711780359',
    },
    WINNER: {
      ACTION:    'https://docs.google.com/forms/d/e/1FAIpQLSctHLTgJAx7jO6UmsXsI6hnJJdhVADKxIqwIh8aQPyZ_G7fFA/formResponse',
      PLAYER:    'entry.2053224380', PARTNER:'entry.1249763927',
      TEAMNAME:  'entry.734626734',  TIMESTAMP:'entry.1927500522',
    },
  },

  K: {
    HANDLE:'lc_handle', ROLE:'lc_role', PARTNER:'lc_partner',
    TEAMNAME:'lc_team', KAKTUS_DONE:'lc_kaktus', STOPS_DONE:'lc_stops',
    WON:'lc_won', LANG:'lc_lang',
  },

  set(k,v)   { localStorage.setItem(k,String(v)); },
  get(k)     { return localStorage.getItem(k); },
  clearAll() {
    const savedLang = this.get(this.K.LANG); // preserve language across game reset
    Object.values(this.K).forEach(k=>localStorage.removeItem(k));
    if (savedLang) this.set(this.K.LANG, savedLang);
  },

  getStops() { try { return JSON.parse(this.get(this.K.STOPS_DONE)||'[]'); } catch { return []; } },
  addStop(id) { const d=this.getStops(); if(!d.includes(id)){d.push(id);this.set(this.K.STOPS_DONE,JSON.stringify(d));} },
  stopsForRole(r) { return this.STOPS[r||this.get(this.K.ROLE)]||[]; },
  allStopsDone() { const r=this.get(this.K.ROLE); return r?this.stopsForRole(r).every(s=>this.getStops().includes(s.id)):false; },
  getFragments() { return this.stopsForRole(this.get(this.K.ROLE)).filter(s=>this.getStops().includes(s.id)).map(s=>s.fragment); },

  isHuntLive()  { const n=new Date(); return n>=this.HUNT_START&&n<=this.HUNT_END; },
  isHuntOver()  { return new Date()>this.HUNT_END; },

  validHandle(r) { const h=r.replace(/^@/,'').trim(); return h.length>=2&&/^[a-zA-Z0-9._]+$/.test(h); },
  cleanHandle(r) { return r.replace(/^@/,'').trim().toLowerCase(); },
  norm(s) { return s.toUpperCase().replace(/\s+/g,'').replace(/[^A-Z0-9°#\-]/g,''); },
  now() { return new Date().toLocaleString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}); },

  postForm(key,fields) {
    const cfg=this.FORMS[key];
    if(!cfg||cfg.ACTION.includes('FORM_ID')){console.warn('LOCALI: form '+key+' not configured');return;}
    fetch(cfg.ACTION,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields).toString()}).catch(err=>console.warn('LOCALI: form submit failed',err));
  },

  // ── Language ───────────────────────────────────────────────
  getLang()     { return this.get(this.K.LANG)||'en'; },
  setLang(lang) { this.set(this.K.LANG,lang); },
  t(key)        { return (I18N[key]||{})[this.getLang()]||(I18N[key]||{})['en']||key; },

  applyLang() {
    const lang=this.getLang();
    document.querySelectorAll('[data-i18n]').forEach(el=>{
      const key=el.getAttribute('data-i18n');
      const val=(I18N[key]||{})[lang]||(I18N[key]||{})['en'];
      if(val!==undefined){ if(el.tagName==='INPUT')el.setAttribute('placeholder',val); else el.innerHTML=val; }
    });
    document.querySelectorAll('[data-i18n-tag]').forEach(el=>{
      const key=el.getAttribute('data-i18n-tag');
      const val=(I18N[key]||{})[lang]||(I18N[key]||{})['en'];
      if(val!==undefined)el.setAttribute('data-tag',val);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{
      const key=el.getAttribute('data-i18n-placeholder');
      const val=(I18N[key]||{})[lang]||(I18N[key]||{})['en'];
      if(val!==undefined)el.setAttribute('placeholder',val);
    });
    document.querySelectorAll('.lang-toggle').forEach(btn=>{
      btn.innerHTML = lang==='en'
        ? '<span class="lang-flag">🇬🇧</span><span class="lang-cur">EN</span><span class="lang-sep">›</span><span class="lang-next">DE</span>'
        : '<span class="lang-flag">🇩🇪</span><span class="lang-cur">DE</span><span class="lang-sep">›</span><span class="lang-next">EN</span>';
      btn.title = lang==='en' ? 'Auf Deutsch wechseln' : 'Switch to English';
      btn.setAttribute('aria-label', btn.title);
    });
    document.documentElement.lang=lang;
  },

  initLangToggle() {
    document.querySelectorAll('.lang-toggle').forEach(btn=>{
      btn.addEventListener('click',()=>{ G.setLang(G.getLang()==='en'?'de':'en'); location.reload(); });
    });
    this.applyLang();
  },
};

// ── Translation dictionary ─────────────────────────────────────────────────────
const I18N = {
  'logo.tagline':        { en:'Welcome', de:'Willkommen' },
  'nav.back.start':      { en:'← Start from the beginning', de:'← Zum Anfang' },
  'nav.back.hunt':       { en:'← Back to my hunt', de:'← Zurück zur Jagd' },
  'nav.back.waiting':    { en:'← Back to waiting screen', de:'← Zurück zur Warteseite' },
  'role.a.label':        { en:'⬡ Player A — The Scout', de:'⬡ Spieler A — Der Späher' },
  'role.b.label':        { en:'⬡ Player B — The Historian', de:'⬡ Spieler B — Der Historiker' },
  'step.tag.1':          { en:'Step 1 of 4', de:'Schritt 1 von 4' },
  'step.tag.2':          { en:'Step 2 of 4', de:'Schritt 2 von 4' },
  'step.tag.registered': { en:"You're Registered", de:'Du bist registriert' },
  'step.tag.hunt':       { en:'The Hunt', de:'Die Jagd' },
  'step.tag.kaktus':     { en:'Kaktus Reward', de:'Kaktus Belohnung' },
  'foot.role':           { en:'LOCALI 2.0 · Step 1 · Role & Identity', de:'LOCALI 2.0 · Schritt 1 · Rolle & Identität' },
  'foot.team':           { en:'LOCALI 2.0 · Step 2 · Team Registration', de:'LOCALI 2.0 · Schritt 2 · Teamregistrierung' },
  'foot.waiting':        { en:'LOCALI 2.0 · Bielefeld · 06–11 March 2026', de:'LOCALI 2.0 · Bielefeld · 06.–11. März 2026' },
  'foot.hunt':           { en:'LOCALI 2.0 · The Hunt · Bielefeld', de:'LOCALI 2.0 · Die Jagd · Bielefeld' },
  'foot.kaktus':         { en:'LOCALI 2.0 · Kaktus Reward', de:'LOCALI 2.0 · Kaktus Belohnung' },
  'maps.kaktus':         { en:'Open Kaktus in Google Maps', de:'Kaktus in Google Maps öffnen' },
  'maps.indie':          { en:'Open Indieflavours in Google Maps', de:'Indieflavours in Google Maps öffnen' },
  'not.registered.title':{ en:'Register first', de:'Zuerst registrieren' },
  'not.registered.body': { en:"You haven't started the game yet. Go back to the LOCALI home page to set up your account.", de:'Du hast das Spiel noch nicht gestartet. Geh zur LOCALI-Startseite, um dein Konto einzurichten.' },

  // index
  'index.hero.label':    { en:'Bielefeld · 06–11 March 2026', de:'Bielefeld · 06.–11. März 2026' },
  'index.hero.h1':       { en:'A city game for two strangers', de:'Ein Stadtspiel für zwei Fremde' },
  'index.hero.p':        { en:"You don't know your partner yet. By the end of this quest you will have explored Bielefeld together, eaten well, and possibly won €100.", de:'Du kennst deinen Partner noch nicht. Am Ende dieser Jagd werdet ihr Bielefeld gemeinsam erkundet, gut gegessen und vielleicht €100 gewonnen haben.' },
  'index.rewards.tag':   { en:'The Rewards', de:'Die Belohnungen' },
  'index.rewards.h3':    { en:'What you can win', de:'Was du gewinnen kannst' },
  'index.rewards.li1':   { en:'<strong>20% off</strong> at Kaktus Mexican Food — any player, any time, no expiry', de:'<strong>20% Rabatt</strong> bei Kaktus Mexican Food — für jeden Spieler, jederzeit, kein Ablaufdatum' },
  'index.rewards.li2':   { en:'<strong>50% off</strong> for Lassi at Indieflavours Bielefeld — every team that completes the hunt', de:'<strong>50% Rabatt</strong> auf Lassi bei Indieflavours Bielefeld — für jedes Team, das die Jagd abschließt' },
  'index.rewards.li3':   { en:'<strong>€100 voucher</strong> at Indieflavours Bielefeld — the first team to finish', de:'<strong>€100 Gutschein</strong> bei Indieflavours Bielefeld — für das erste Team, das fertig wird' },
  'index.how.tag':       { en:'How It Works', de:'Wie es funktioniert' },
  'index.how.h3':        { en:'Two players. Six hidden stickers. One big prize.', de:'Zwei Spieler. Sechs versteckte Sticker. Ein großer Preis.' },
  'index.how.li1':       { en:'Choose your role — <strong>Player A</strong> or <strong>Player B</strong>', de:'Wähle deine Rolle — <strong>Spieler A</strong> oder <strong>Spieler B</strong>' },
  'index.how.li2':       { en:'Find a partner on Instagram with the opposite role and form a team', de:'Finde auf Instagram einen Partner mit der entgegengesetzten Rolle und bilde ein Team' },
  'index.how.li3':       { en:'Visit <strong>Kaktus</strong> any time — find the code sticker inside for your personal 20% discount', de:'Besuche <strong>Kaktus</strong> jederzeit — finde den Code-Sticker drinnen für deinen persönlichen 20% Rabatt' },
  'index.how.li4':       { en:'On <strong>Saturday 07.03 at 12:00</strong> LOCALI posts on Instagram — your first location link is in that post', de:'Am <strong>Samstag, 07.03. um 12:00</strong> postet LOCALI auf Instagram — dein erster Standortlink ist in diesem Post' },
  'index.how.li5':       { en:'Go there, find the LOCALI sticker, enter the code — it reveals your fragment and your next location', de:'Geh dorthin, finde den LOCALI-Sticker, gib den Code ein — er enthüllt dein Fragment und deinen nächsten Standort' },
  'index.how.li6':       { en:'After 3 stops each, call your partner — enter all 6 fragments together to decode the secret address', de:'Nach je 3 Stops: ruf deinen Partner an — gebt alle 6 Fragmente zusammen ein, um die geheime Adresse zu entschlüsseln' },
  'index.how.li7':       { en:'Go to that address, find the final sticker, enter the code — claim your prize', de:'Geh zu dieser Adresse, finde den letzten Sticker, gib den Code ein — hol dir deinen Preis' },
  'index.rules.tag':     { en:'Rules', de:'Regeln' },
  'index.rules.h3':      { en:'Before you start', de:'Bevor du anfängst' },
  'index.rules.li1':     { en:'Real Instagram account required — handles are validated', de:'Echtes Instagram-Konto erforderlich — Handles werden überprüft' },
  'index.rules.li2':     { en:'The Kaktus discount is <strong>personal</strong> — no partner needed, valid any time', de:'Der Kaktus-Rabatt ist <strong>persönlich</strong> — kein Partner nötig, jederzeit gültig' },
  'index.rules.li3':     { en:'Instagram post goes live <strong>Saturday 07.03 at 12:00</strong> — register from Friday', de:'Instagram-Post geht <strong>Samstag 07.03. um 12:00</strong> online — ab Freitag registrieren' },
  'index.rules.li4':     { en:'Hunt closes <strong>Wednesday 11.03 at midnight</strong>', de:'Jagd endet <strong>Mittwoch 11.03. um Mitternacht</strong>' },
  'index.rules.li5':     { en:'You visit <strong>different locations</strong> from your partner — fragments only work combined', de:'Du besuchst <strong>andere Orte</strong> als dein Partner — Fragmente funktionieren nur kombiniert' },
  'index.rules.li6':     { en:'Location names stay hidden until you enter the correct sticker code', de:'Ortsnamen bleiben verborgen, bis du den richtigen Sticker-Code eingibst' },
  'index.timeline.tag':  { en:'Timeline', de:'Zeitplan' },
  'index.timeline.h3':   { en:'Schedule', de:'Ablauf' },
  'index.timeline.li1':  { en:'<strong>Fri 06.03 →</strong> Register here, find your partner, visit Kaktus any time', de:'<strong>Fr 06.03 →</strong> Hier registrieren, Partner finden, Kaktus jederzeit besuchen' },
  'index.timeline.li2':  { en:'<strong>Sat 07.03, 12:00 →</strong> Instagram post live — first stop links published', de:'<strong>Sa 07.03, 12:00 →</strong> Instagram-Post live — erste Stop-Links veröffentlicht' },
  'index.timeline.li3':  { en:'<strong>Wed 11.03, 23:59 →</strong> Hunt ends — Indieflavours prize expires', de:'<strong>Mi 11.03, 23:59 →</strong> Jagd endet — Indieflavours-Preis verfällt' },
  'index.cta':           { en:"I understand — Let's go →", de:"Verstanden — Los geht's →" },

  // role
  'role.hero.label':     { en:'Your Identity', de:'Deine Identität' },
  'role.hero.h1':        { en:'Choose your role', de:'Wähle deine Rolle' },
  'role.hero.p':         { en:'Your role decides which locations you visit and which fragments you collect. You and your partner must have opposite roles — the puzzle only works that way.', de:'Deine Rolle bestimmt, welche Orte du besuchst und welche Fragmente du sammelst. Du und dein Partner müssen entgegengesetzte Rollen haben — das Rätsel funktioniert nur so.' },
  'role.a.title':        { en:'The Scout', de:'Der Späher' },
  'role.a.desc':         { en:'Physical observation. You count, measure, and look.', de:'Physische Beobachtung. Du zählst, misst und schaust.' },
  'role.b.title':        { en:'The Historian', de:'Der Historiker' },
  'role.b.desc':         { en:'Names, places, and meaning. You read and interpret.', de:'Namen, Orte und Bedeutung. Du liest und interpretierst.' },
  'role.err.pick':       { en:'Please choose a role before continuing.', de:'Bitte wähle eine Rolle, bevor du weitermachst.' },
  'role.identity.tag':   { en:'Your Identity', de:'Deine Identität' },
  'role.identity.h3':    { en:'Your Instagram handle', de:'Dein Instagram-Handle' },
  'role.identity.p':     { en:'This is how partners find you and how we verify your team. Enter your real handle — we check the format.', de:'So finden dich Partner und so überprüfen wir dein Team. Gib deinen echten Handle ein — wir prüfen das Format.' },
  'role.handle.label':   { en:'Instagram Handle', de:'Instagram-Handle' },
  'role.handle.ph':      { en:'e.g. your_handle (without @)', de:'z.B. dein_handle (ohne @)' },
  'role.handle.hint':    { en:'Only letters, numbers, dots and underscores. Min 2 characters.', de:'Nur Buchstaben, Zahlen, Punkte und Unterstriche. Min. 2 Zeichen.' },
  'role.handle.ok':      { en:'✓ looks valid', de:'✓ sieht gültig aus' },
  'role.handle.err':     { en:'✗ Invalid format. Use letters, numbers, dots, underscores only.', de:'✗ Ungültiges Format. Nur Buchstaben, Zahlen, Punkte, Unterstriche.' },
  'role.confirm.tag':    { en:'Confirm Your Choices', de:'Auswahl bestätigen' },
  'role.confirm.h3':     { en:'Before you continue', de:'Bevor du weitermachst' },
  'role.confirm.row.role':{ en:'Role', de:'Rolle' },
  'role.confirm.row.handle':{ en:'Handle', de:'Handle' },
  'role.confirm.change': { en:'✕ Change my choices', de:'✕ Auswahl ändern' },
  'role.a.full':         { en:'Player A — The Scout', de:'Spieler A — Der Späher' },
  'role.b.full':         { en:'Player B — The Historian', de:'Spieler B — Der Historiker' },
  'role.err.handle':     { en:'Please enter a valid Instagram handle.', de:'Bitte gib einen gültigen Instagram-Handle ein.' },
  'role.cta':            { en:'Confirm & Continue →', de:'Bestätigen & Weiter →' },

  // team
  'team.hero.label':     { en:'Find Your Partner', de:'Finde deinen Partner' },
  'team.hero.h1':        { en:'Go to Instagram', de:'Geh zu Instagram' },
  'team.ig.tag':         { en:'Step 1 — Comment', de:'Schritt 1 — Kommentar' },
  'team.ig.h3':          { en:'Post your role on our Instagram', de:'Poste deine Rolle auf unserem Instagram' },
  'team.ig.p':           { en:'Go to the LOCALI post and leave this comment exactly so others can find you:', de:'Geh zum LOCALI-Post und hinterlasse diesen Kommentar genau so, damit andere dich finden können:' },
  'team.comment.label':  { en:'Copy this comment', de:'Diesen Kommentar kopieren' },
  'team.ig.btn':         { en:'→ Open the LOCALI Instagram Post', de:'→ LOCALI Instagram-Post öffnen' },
  'team.find.tag':       { en:'Step 2 — Find & DM', de:'Schritt 2 — Finden & DM' },
  'team.find.h3':        { en:'Find someone with the opposite role', de:'Finde jemanden mit der entgegengesetzten Rolle' },
  'team.find.li1':       { en:'Browse the comments for someone who posted the <strong>opposite role</strong>', de:'Suche in den Kommentaren nach jemandem, der die <strong>entgegengesetzte Rolle</strong> gepostet hat' },
  'team.find.li2':       { en:'Send them a DM — introduce yourself', de:'Schick ihnen eine DM — stell dich vor' },
  'team.find.li3':       { en:'Together, decide on a <strong>team name</strong> (anything you like)', de:'Entscheidet gemeinsam einen <strong>Teamnamen</strong> (was ihr möchtet)' },
  'team.find.li4':       { en:'Then both of you come back here and register your team', de:'Dann kommt ihr beide hierher zurück und registriert euer Team' },
  'team.divider':        { en:'once you have a partner', de:'sobald du einen Partner hast' },
  'team.register.tag':   { en:'Step 3 — Register Your Team', de:'Schritt 3 — Team registrieren' },
  'team.register.h3':    { en:'Enter your team details', de:'Teamdetails eingeben' },
  'team.register.p':     { en:"Both players must register with the exact same team name. We'll log both entries — that's fine.", de:'Beide Spieler müssen mit exakt demselben Teamnamen registrieren. Wir protokollieren beide Einträge — das ist in Ordnung.' },
  'team.partner.label':  { en:"Partner's Instagram Handle", de:'Instagram-Handle des Partners' },
  'team.partner.ph':     { en:"your partner's handle (without @)", de:"Handle deines Partners (ohne @)" },
  'team.partner.hint':   { en:"Enter your partner's real Instagram handle.", de:'Gib den echten Instagram-Handle deines Partners ein.' },
  'team.partner.self':   { en:"✗ You can't be your own partner.", de:'✗ Du kannst nicht dein eigener Partner sein.' },
  'team.partner.err':    { en:'✗ Invalid format.', de:'✗ Ungültiges Format.' },
  'team.teamname.label': { en:'Team Name', de:'Teamname' },
  'team.teamname.ph':    { en:'agree on this with your partner first', de:'erst mit deinem Partner absprechen' },
  'team.teamname.hint':  { en:'Min 2 characters. Agree with your partner before submitting.', de:'Min. 2 Zeichen. Erst mit deinem Partner absprechen.' },
  'team.teamname.ok':    { en:'✓ Team name set', de:'✓ Teamname gesetzt' },
  'team.teamname.short': { en:'✗ Too short.', de:'✗ Zu kurz.' },
  'team.err.partner':    { en:'Please enter a valid partner Instagram handle.', de:'Bitte gib einen gültigen Partner-Instagram-Handle ein.' },
  'team.err.teamname':   { en:'Please enter a team name (at least 2 characters).', de:'Bitte gib einen Teamnamen ein (mindestens 2 Zeichen).' },
  'team.register.btn':   { en:'Register Team →', de:'Team registrieren →' },
  'team.success.alert':  { en:'✓ Team registered! Both entries logged.', de:'✓ Team registriert! Beide Einträge gespeichert.' },
  'team.success.tag':    { en:'Your Team', de:'Dein Team' },
  'team.success.you':    { en:'Your handle', de:'Dein Handle' },
  'team.success.partner':{ en:'Partner', de:'Partner' },
  'team.success.role':   { en:'Your role', de:'Deine Rolle' },
  'team.next.tag':       { en:"What's Next", de:'Was als nächstes' },
  'team.next.h3':        { en:'Now head to Kaktus', de:'Jetzt zu Kaktus gehen' },
  'team.next.p':         { en:'Go to <strong>Kaktus Mexican Food</strong> and claim your 20% team discount. Inside the restaurant, find the secret LOCALI code — it\'s hidden somewhere in the space. Enter it in the next screen to unlock your voucher.', de:'Geh zu <strong>Kaktus Mexican Food</strong> und hole dir deinen 20% Teamrabatt. Finde drinnen den geheimen LOCALI-Code — er ist irgendwo im Raum versteckt. Gib ihn im nächsten Bildschirm ein, um deinen Gutschein freizuschalten.' },
  'team.kaktus.btn':     { en:"I'm at Kaktus → Enter Code", de:'Ich bin bei Kaktus → Code eingeben' },
  'team.comment.a':      { en:'🔵 PLAYER A — The Scout. Looking for a Player B (Historian) to team up! #LOCALIQuest', de:'🔵 SPIELER A — Der Späher. Suche Spieler B (Historiker) zum Zusammenspielen! #LOCALIQuest' },
  'team.comment.b':      { en:'🟡 PLAYER B — The Historian. Looking for a Player A (Scout) to team up! #LOCALIQuest', de:'🟡 SPIELER B — Der Historiker. Suche Spieler A (Späher) zum Zusammenspielen! #LOCALIQuest' },

  // kaktus
  'kaktus.gate.err':     { en:'Set up your role first.', de:'Richte zuerst deine Rolle ein.' },
  'kaktus.gate.link':    { en:'← Go to Step 1', de:'← Zu Schritt 1' },
  'kaktus.hero.label':   { en:'Kaktus Mexican Food', de:'Kaktus Mexican Food' },
  'kaktus.hero.h1':      { en:'Find the hidden code', de:'Finde den versteckten Code' },
  'kaktus.hero.p':       { en:"You're at Kaktus. Somewhere inside the restaurant — on the menu, a sticker, the wall — there is a printed LOCALI code. Look for it. Enter it below to unlock your personal 20% discount.", de:'Du bist bei Kaktus. Irgendwo im Restaurant — auf der Speisekarte, einem Sticker, der Wand — gibt es einen gedruckten LOCALI-Code. Suche danach. Gib ihn unten ein, um deinen persönlichen 20% Rabatt freizuschalten.' },
  'kaktus.info':         { en:'This reward is <strong>yours alone</strong> — no partner or team needed. You can use it any time, even after the hunt ends.', de:'Diese Belohnung gehört <strong>nur dir</strong> — kein Partner oder Team nötig. Du kannst sie jederzeit nutzen, auch nach dem Ende der Jagd.' },
  'kaktus.code.label':   { en:'Kaktus Secret Code', de:'Kaktus Geheimcode' },
  'kaktus.code.ph':      { en:'The code you found inside Kaktus', de:'Der Code, den du in Kaktus gefunden hast' },
  'kaktus.code.hint':    { en:'Not case-sensitive. Enter exactly what you see on the sticker.', de:'Groß-/Kleinschreibung egal. Gib genau ein, was du auf dem Sticker siehst.' },
  'kaktus.code.err':     { en:"✗ That's not the code. Keep looking inside Kaktus.", de:'✗ Das ist nicht der Code. Schau weiter in Kaktus.' },
  'kaktus.cta':          { en:'Unlock My 20% Voucher →', de:'Meinen 20% Gutschein freischalten →' },
  'kaktus.tip':          { en:'💡 The code is physically inside the restaurant — you need to be there to find it.', de:'💡 Der Code ist physisch im Restaurant — du musst dort sein, um ihn zu finden.' },
  'kaktus.divider':      { en:'unlocked ✓', de:'freigeschaltet ✓' },
  'kaktus.v.lbl1':       { en:'LOCALI Personal Reward', de:'LOCALI Persönliche Belohnung' },
  'kaktus.v.lbl2':       { en:'Off Your Entire Order', de:'Auf deine gesamte Bestellung' },
  'kaktus.v.once':       { en:'Screenshot this — show it to the waiter or at the cash', de:'Screenshot machen — dem Kellner oder an der Kasse zeigen' },
  'kaktus.redeem.info':  { en:'Show this screen at the cash or to your waiter. Take a screenshot first. Tap below once your discount has been applied.', de:'Zeige diesen Bildschirm an der Kasse oder deinem Kellner. Mach zuerst einen Screenshot. Tippe unten, sobald dein Rabatt angewendet wurde.' },
  'kaktus.redeem.btn':   { en:'✓ Mark as Redeemed', de:'✓ Als eingelöst markieren' },
  'kaktus.redeem.ok':    { en:'✅ Voucher redeemed. Enjoy your meal! 🌮', de:'✅ Gutschein eingelöst. Guten Appetit! 🌮' },
  'kaktus.redeem.confirm':{ en:'Has your discount been applied? Tap OK to mark as used.', de:'Wurde dein Rabatt angewendet? Tippe OK, um es als verwendet zu markieren.' },
  'kaktus.hunt.tag':     { en:'Meanwhile', de:'In der Zwischenzeit' },
  'kaktus.hunt.h3':      { en:'The hunt is coming', de:'Die Jagd kommt' },
  'kaktus.hunt.p':       { en:'On <strong>Friday 06.03 at 12:00</strong>, LOCALI will post on Instagram. That post contains your hunt link. Tap the link for your role and begin the city hunt — 3 locations, encoded fragments, and a secret restaurant to decode.', de:'Am <strong>Freitag 06.03. um 12:00</strong> postet LOCALI auf Instagram. Dieser Post enthält deinen Jagd-Link. Tippe auf den Link für deine Rolle und beginne die Stadtjagd — 3 Standorte, kodierte Fragmente und ein geheimes Restaurant zum Entschlüsseln.' },

  // waiting
  'waiting.cd.label':    { en:'Instagram post goes live in', de:'Instagram-Post geht live in' },
  'waiting.cd.live':     { en:'LIVE NOW', de:'JETZT LIVE' },
  'waiting.cd.live.sub': { en:'Hunt is live — check Instagram!', de:'Jagd ist live — Instagram checken!' },
  'waiting.cd.ended':    { en:'Hunt ended', de:'Jagd beendet' },
  'waiting.cd.sub':      { en:'Saturday · 07.03.2026 · 12:00', de:'Samstag · 07.03.2026 · 12:00' },
  'waiting.ig.tag':      { en:'What Happens on Saturday', de:'Was am Samstag passiert' },
  'waiting.ig.h3':       { en:'LOCALI posts on Instagram — not a story', de:'LOCALI postet auf Instagram — kein Story' },
  'waiting.ig.p':        { en:'On <strong>Saturday 07.03 at 12:00</strong>, LOCALI publishes a post (it stays live all week — not a 24-hour story). That post contains <strong>two links</strong>:', de:'Am <strong>Samstag 07.03. um 12:00</strong> veröffentlicht LOCALI einen Post (er bleibt die ganze Woche live — kein 24-Stunden-Story). Dieser Post enthält <strong>zwei Links</strong>:' },
  'waiting.ig.li1':      { en:'One link for <strong>Player A — The Scout</strong>', de:'Ein Link für <strong>Spieler A — Der Späher</strong>' },
  'waiting.ig.li2':      { en:'One link for <strong>Player B — The Historian</strong>', de:'Ein Link für <strong>Spieler B — Der Historiker</strong>' },
  'waiting.ig.p2':       { en:"Tap <strong>your</strong> role's link. It takes you to your first stop. <strong>Do not tap your partner's link</strong> — their clues are different from yours.", de:"Tippe auf den Link <strong>deiner</strong> Rolle. Er bringt dich zu deinem ersten Stop. <strong>Tippe nicht auf den Link deines Partners</strong> — seine Hinweise sind anders als deine." },
  'waiting.stops.tag':   { en:'How Stops Work', de:'Wie Stops funktionieren' },
  'waiting.stops.h3':    { en:'Physical sticker codes', de:'Physische Sticker-Codes' },
  'waiting.stops.li1':   { en:'Arrive at your location', de:'Komm an deinem Standort an' },
  'waiting.stops.li2':   { en:'Find the small <strong>LOCALI sticker</strong> — it has a short code written on it', de:'Finde den kleinen <strong>LOCALI-Sticker</strong> — darauf steht ein kurzer Code' },
  'waiting.stops.li3':   { en:'Enter the code on your screen — it must match exactly', de:'Gib den Code auf deinem Bildschirm ein — er muss genau übereinstimmen' },
  'waiting.stops.li4':   { en:'Correct code reveals your <strong>encoded fragment</strong> and a clue to the next location', de:'Richtiger Code enthüllt dein <strong>kodiertes Fragment</strong> und einen Hinweis zum nächsten Standort' },
  'waiting.stops.li5':   { en:'After 3 stops: call your partner and enter all 6 fragments together to decode the final address', de:'Nach 3 Stops: ruf deinen Partner an und gebt alle 6 Fragmente zusammen ein, um die finale Adresse zu entschlüsseln' },
  'waiting.kaktus.tag':  { en:'Meanwhile — Kaktus', de:'In der Zwischenzeit — Kaktus' },
  'waiting.kaktus.h3':   { en:'Visit Kaktus any time you like', de:'Besuche Kaktus wann immer du möchtest' },
  'waiting.kaktus.p':    { en:'No need to wait for Saturday. Visit <strong>Kaktus Mexican Food</strong>, find the code sticker inside, and claim your personal 20% discount. No team or partner needed. No expiry.', de:'Kein Grund, auf Samstag zu warten. Besuche <strong>Kaktus Mexican Food</strong>, finde den Code-Sticker drinnen und hol dir deinen persönlichen 20% Rabatt. Kein Team oder Partner nötig. Kein Ablaufdatum.' },
  'waiting.kaktus.btn':  { en:'→ Kaktus code entry', de:'→ Kaktus Code eingeben' },
  'waiting.reg.tag':     { en:'Your Registration', de:'Deine Registrierung' },
  'waiting.reg.you':     { en:'Your handle', de:'Dein Handle' },
  'waiting.reg.partner': { en:'Partner', de:'Partner' },
  'waiting.reg.role':    { en:'Your role', de:'Deine Rolle' },
  'waiting.reg.kaktus':  { en:'Kaktus', de:'Kaktus' },
  'waiting.kaktus.done': { en:'✓ Claimed', de:'✓ Eingelöst' },
  'waiting.kaktus.not':  { en:'Not yet — visit Kaktus any time', de:'Noch nicht — Kaktus jederzeit besuchen' },
  'waiting.ig.btn':      { en:'Follow @locali_bielefeld on Instagram', de:'@locali_bielefeld auf Instagram folgen' },
  'waiting.saved':       { en:'💾 Your data is saved on this device. Return here any time.', de:'💾 Deine Daten sind auf diesem Gerät gespeichert. Jederzeit wiederkommen.' },
  'waiting.noreg':       { en:'No team registered yet', de:'Noch kein Team registriert' },

  // stop pages
  'stop.wrong.a':        { en:'This stop is for Player A — The Scout. You have the other role.', de:'Dieser Stop ist für Spieler A — Den Späher. Du hast die andere Rolle.' },
  'stop.wrong.b':        { en:'This stop is for Player B — The Historian. You have the other role.', de:'Dieser Stop ist für Spieler B — Den Historiker. Du hast die andere Rolle.' },
  'stop.already.ok':     { en:'✓ You already collected this fragment.', de:'✓ Du hast dieses Fragment bereits gesammelt.' },
  'stop.already.next.tag':{ en:'Next Location — Clue', de:'Nächster Standort — Hinweis' },
  'stop.already.next.h3':{ en:'Your next stop', de:'Dein nächster Stop' },
  'stop.alldone.tag':    { en:'All Done', de:'Alles erledigt' },
  'stop.alldone.h3':     { en:'You have all your fragments', de:'Du hast alle deine Fragmente' },
  'stop.alldone.p':      { en:'Go back to the hunt overview to decode with your partner.', de:'Geh zurück zur Jagdübersicht, um mit deinem Partner zu entschlüsseln.' },
  'stop.hero.h1':        { en:'Go to this location', de:'Geh zu diesem Standort' },
  'stop.hero.p':         { en:'Head to the coordinates below. Once you arrive, find the small LOCALI sticker and enter the code printed on it.', de:'Geh zu den unten stehenden Koordinaten. Wenn du ankommst, finde den kleinen LOCALI-Sticker und gib den darauf gedruckten Code ein.' },
  'stop.dest.tag':       { en:'Your Destination', de:'Dein Ziel' },
  'stop.sticker.info':   { en:"🔍 Once you're there — find the small LOCALI sticker on a wall, sign, bench, or post near the landmark.", de:'🔍 Wenn du dort bist — finde den kleinen LOCALI-Sticker an einer Wand, einem Schild, einer Bank oder einem Pfosten in der Nähe des Wahrzeichens.' },
  'stop.code.label':     { en:'Code on the LOCALI sticker', de:'Code auf dem LOCALI-Sticker' },
  'stop.code.ph':        { en:'e.g. ABC-1', de:'z.B. ABC-1' },
  'stop.code.hint':      { en:'Enter exactly what you see — dashes and numbers included.', de:'Gib genau ein, was du siehst — inklusive Bindestriche und Zahlen.' },
  'stop.code.err':       { en:"✗ That code doesn't match. Look more carefully — the sticker is small.", de:'✗ Dieser Code stimmt nicht. Schau genauer — der Sticker ist klein.' },
  'stop.submit':         { en:'Submit Code →', de:'Code einreichen →' },
  'stop.frag.warn':      { en:'⚠ Write this down <strong>exactly</strong> — every symbol and character matters. Do not share it until you have all 3.', de:'⚠ Schreib das <strong>genau</strong> auf — jedes Symbol und jedes Zeichen zählt. Teile es nicht, bis du alle 3 hast.' },
  'stop.next.tag':       { en:'Your Next Location — Clue', de:'Dein nächster Standort — Hinweis' },
  'stop.next.h3':        { en:'Head to your next stop', de:'Geh zu deinem nächsten Stop' },
  'stop.last.tag':       { en:'Last Stop', de:'Letzter Stop' },
  'stop.last.h3':        { en:'You have all 3 fragments', de:'Du hast alle 3 Fragmente' },
  'stop.last.p':         { en:'Call your partner and make sure they also have all 3 of theirs. Then head back to the hunt overview to decode together.', de:'Ruf deinen Partner an und stelle sicher, dass er auch alle 3 seiner Fragmente hat. Geh dann zur Jagdübersicht, um gemeinsam zu entschlüsseln.' },
  'stop.save.mid':       { en:'Saved — Continue →', de:'Gespeichert — Weiter →' },
  'stop.save.last':      { en:'Saved — Go to Decoder →', de:'Gespeichert — Zum Decoder →' },
  'stop.back.hunt':      { en:'← Back to hunt overview', de:'← Zurück zur Jagdübersicht' },
  'stop.maps.open':      { en:'Open in Google Maps →', de:'In Google Maps öffnen →' },

  // hunt
  'hunt.gate.err':       { en:'Register first.', de:'Zuerst registrieren.' },
  'hunt.gate.link':      { en:'← Start from the beginning', de:'← Zum Anfang' },
  'hunt.pre.label':      { en:'Not Live Yet', de:'Noch nicht live' },
  'hunt.pre.h1':         { en:'Hunt starts Saturday', de:'Jagd startet Samstag' },
  'hunt.pre.p':          { en:'On <strong>Saturday 07.03 at 12:00</strong> LOCALI posts on Instagram. That post has your first stop link. Come back then — or tap the button below to watch for the post.', de:'Am <strong>Samstag 07.03. um 12:00</strong> postet LOCALI auf Instagram. Dieser Post hat deinen ersten Stop-Link. Komm dann wieder — oder tippe unten, um auf den Post zu warten.' },
  'hunt.pre.cd.label':   { en:'Post live in', de:'Post geht live in' },
  'hunt.pre.ig.btn':     { en:'Watch @locali_bielefeld on Instagram', de:'@locali_bielefeld auf Instagram beobachten' },
  'hunt.over.label':     { en:'Hunt Closed', de:'Jagd beendet' },
  'hunt.over.h1':        { en:'The quest has ended', de:'Die Quest ist beendet' },
  'hunt.over.p':         { en:'The LOCALI Bielefeld Quest ran 06–11 March 2026. Thank you for taking part.', de:'Die LOCALI Bielefeld Quest lief vom 06.–11. März 2026. Danke für deine Teilnahme.' },
  'hunt.nostops.label':  { en:'Step 1 — Your First Location', de:'Schritt 1 — Dein erster Standort' },
  'hunt.nostops.h1':     { en:'Go to Instagram', de:'Geh zu Instagram' },
  'hunt.nostops.p':      { en:"The LOCALI post is live. Open it and tap the link for your role. It takes you directly to your first stop. Come back here after you've found the sticker and entered the code.", de:'Der LOCALI-Post ist live. Öffne ihn und tippe auf den Link für deine Rolle. Er bringt dich direkt zu deinem ersten Stop. Komm hierher zurück, nachdem du den Sticker gefunden und den Code eingegeben hast.' },
  'hunt.nostops.card.tag':{ en:'Your Link', de:'Dein Link' },
  'hunt.nostops.card.p': { en:'The post has a link for Player A and a separate link for Player B. Tap yours only.', de:'Der Post hat einen Link für Spieler A und einen separaten für Spieler B. Tippe nur auf deinen.' },
  'hunt.nostops.prompt.a':{ en:'→ Tap the Player A link in the LOCALI post', de:'→ Tippe auf den Spieler-A-Link im LOCALI-Post' },
  'hunt.nostops.prompt.b':{ en:'→ Tap the Player B link in the LOCALI post', de:'→ Tippe auf den Spieler-B-Link im LOCALI-Post' },
  'hunt.nostops.ig.btn': { en:'Open LOCALI on Instagram →', de:'LOCALI auf Instagram öffnen →' },
  'hunt.progress.h1':    { en:'Keep going', de:'Weiter so' },
  'hunt.progress.frags.tag':{ en:'Your Fragments So Far', de:'Deine bisherigen Fragmente' },
  'hunt.progress.frags.h3':{ en:"What you've collected", de:'Was du gesammelt hast' },
  'hunt.progress.frags.note':{ en:"Write these down. Don't share them until you have all 3.", de:'Schreib diese auf. Teile sie nicht, bis du alle 3 hast.' },
  'hunt.progress.next.tag':{ en:'Your Next Stop', de:'Dein nächster Stop' },
  'hunt.progress.next.h3':{ en:'Head to your next location', de:'Geh zu deinem nächsten Standort' },
  'hunt.progress.stop.label':{ en:'Stop', de:'Stop' },
  'hunt.decoder.label':  { en:'All 3 Stops Complete', de:'Alle 3 Stops abgeschlossen' },
  'hunt.decoder.h1':     { en:'Decode together', de:'Gemeinsam entschlüsseln' },
  'hunt.decoder.p':      { en:'Call your partner. Once you both have all your fragments ready, enter them below. <strong>Both boxes must be exactly right</strong> — the address only appears when both match.', de:'Ruf deinen Partner an. Sobald ihr beide alle Fragmente bereit habt, gebt sie unten ein. <strong>Beide Felder müssen exakt stimmen</strong> — die Adresse erscheint nur, wenn beide übereinstimmen.' },
  'hunt.decoder.own.tag':{ en:'Your 3 Fragments', de:'Deine 3 Fragmente' },
  'hunt.decoder.own.h3': { en:'What you collected', de:'Was du gesammelt hast' },
  'hunt.decoder.own.p':  { en:'Read these out loud to your partner. Ask them to read theirs back to you.', de:'Lies diese deinem Partner laut vor. Bitte ihn, seine dir vorzulesen.' },
  'hunt.decoder.box.tag':{ en:'Enter All 6 Fragments', de:'Alle 6 Fragmente eingeben' },
  'hunt.decoder.box.h3': { en:'Type the combined fragments', de:'Die kombinierten Fragmente eingeben' },
  'hunt.decoder.box.p':  { en:"Enter each player's 3 fragments separated by spaces, exactly as they appeared — every symbol counts. Both boxes must be correct at the same time.", de:"Gib die 3 Fragmente jedes Spielers durch Leerzeichen getrennt ein, genau wie sie erschienen sind — jedes Symbol zählt. Beide Felder müssen gleichzeitig korrekt sein." },
  'hunt.decoder.box.a.label':{ en:'Player A — The Scout (3 fragments)', de:'Spieler A — Der Späher (3 Fragmente)' },
  'hunt.decoder.box.b.label':{ en:'Player B — The Historian (3 fragments)', de:'Spieler B — Der Historiker (3 Fragmente)' },
  'hunt.decoder.box.ph': { en:'fragment-1 fragment-2 fragment-3', de:'Fragment-1 Fragment-2 Fragment-3' },
  'hunt.decoder.hint.a': { en:"Enter Player A's 3 fragments with spaces between them.", de:"Gib die 3 Fragmente von Spieler A mit Leerzeichen dazwischen ein." },
  'hunt.decoder.hint.b': { en:"Enter Player B's 3 fragments with spaces between them.", de:"Gib die 3 Fragmente von Spieler B mit Leerzeichen dazwischen ein." },
  'hunt.decoder.hint.ok':{ en:'✓ Correct', de:'✓ Richtig' },
  'hunt.decoder.hint.err':{ en:"✗ Doesn't match — check every character.", de:'✗ Stimmt nicht überein — prüfe jedes Zeichen.' },
  'hunt.decoder.prefill':{ en:'✓ Pre-filled from your stops — confirm and have your partner fill theirs.', de:'✓ Aus deinen Stops vorausgefüllt — bestätige und lass deinen Partner seine ausfüllen.' },
  'hunt.decoder.err.both':{ en:'✗ Both boxes have errors. Copy each fragment exactly — symbols and case matter.', de:'✗ Beide Felder haben Fehler. Kopiere jedes Fragment genau — Symbole und Groß-/Kleinschreibung zählen.' },
  'hunt.decoder.err.a':  { en:"✗ Player A's fragments don't match. Check for typos.", de:"✗ Fragmente von Spieler A stimmen nicht. Auf Tippfehler prüfen." },
  'hunt.decoder.err.b':  { en:"✗ Player B's fragments don't match. Check for typos.", de:"✗ Fragmente von Spieler B stimmen nicht. Auf Tippfehler prüfen." },
  'hunt.decoder.btn':    { en:'Decode the Address →', de:'Adresse entschlüsseln →' },
  'hunt.fragment.label': { en:'Fragment', de:'Fragment' },
  'hunt.reveal.divider': { en:'decoding…', de:'entschlüsselt…' },
  'hunt.final.tag':      { en:'The Destination', de:'Das Ziel' },
  'hunt.final.h3':       { en:"You've found the address", de:'Du hast die Adresse gefunden' },
  'hunt.final.sticker.tag':{ en:'Final Step — At Indieflavours', de:'Letzter Schritt — Bei Indieflavours' },
  'hunt.final.sticker.h3':{ en:'Find the LOCALI sticker at the entrance', de:'Finde den LOCALI-Sticker am Eingang' },
  'hunt.final.sticker.p':{ en:"You're at Mauerstraße 52. Look for the small LOCALI sticker at the entrance. Enter the code written on it.", de:'Du bist in der Mauerstraße 52. Suche nach dem kleinen LOCALI-Sticker am Eingang. Gib den darauf geschriebenen Code ein.' },
  'hunt.final.code.label':{ en:'Final Code', de:'Finaler Code' },
  'hunt.final.code.ph':  { en:'Code from the sticker at Indieflavours', de:'Code vom Sticker bei Indieflavours' },
  'hunt.final.code.err': { en:'✗ Not the right code. Find the LOCALI sticker at the Indieflavours entrance.', de:'✗ Nicht der richtige Code. Finde den LOCALI-Sticker am Indieflavours-Eingang.' },
  'hunt.final.code.btn': { en:'Claim My Prize →', de:'Meinen Preis einlösen →' },
  'hunt.checking.title': { en:'Checking winner status…', de:'Gewinnerstatus prüfen…' },
  'hunt.checking.sub':   { en:'Just a moment', de:'Einen Moment' },
  'hunt.win.sub':        { en:'First team to complete the Bielefeld Sync-Quest', de:'Erstes Team, das die Bielefeld Sync-Quest abschließt' },
  'hunt.win.v.lbl1':     { en:'LOCALI Grand Prize — First Team', de:'LOCALI Hauptpreis — Erstes Team' },
  'hunt.win.v.lbl2':     { en:'Voucher at', de:'Gutschein bei' },
  'hunt.win.v.once':     { en:'Valid 06–11 March 2026 · Screenshot this now · One-time use', de:'Gültig 06.–11. März 2026 · Screenshot jetzt machen · Einmalige Nutzung' },
  'hunt.win.alert':      { en:'🥇 You are the first team to finish. Show this screen at Indieflavours to claim the €100 voucher.', de:'🥇 Ihr seid das erste Team, das fertig ist. Zeige diesen Bildschirm bei Indieflavours, um den €100-Gutschein einzulösen.' },
  'hunt.win.claim.tag':  { en:'At Indieflavours', de:'Bei Indieflavours' },
  'hunt.win.claim.h3':   { en:'How to claim', de:'So einlösen' },
  'hunt.win.claim.li1':  { en:'Show this screen to the waiter or manager', de:'Zeige diesen Bildschirm dem Kellner oder Manager' },
  'hunt.win.claim.li2':  { en:'Staff have been briefed — this is valid', de:'Das Personal wurde informiert — das ist gültig' },
  'hunt.win.claim.li3':  { en:'Take a screenshot as backup right now', de:'Mach jetzt einen Screenshot als Backup' },
  'hunt.win.claim.li4':  { en:'Valid 06–11 March 2026 only', de:'Nur gültig 06.–11. März 2026' },
  'hunt.finish.sub':     { en:'You solved the Bielefeld Sync-Quest', de:'Ihr habt die Bielefeld Sync-Quest gelöst' },
  'hunt.finish.v.lbl1':  { en:'LOCALI Finisher Reward', de:'LOCALI Abschluss-Belohnung' },
  'hunt.finish.v.lbl2':  { en:'On Mango Lassi at', de:'Auf Mango Lassi bei' },
  'hunt.finish.v.once':  { en:'Valid 06–11 March 2026 · Screenshot this now', de:'Gültig 06.–11. März 2026 · Screenshot jetzt machen' },
  'hunt.finish.grand.tag':{ en:'Grand Prize — Already Claimed', de:'Hauptpreis — Bereits eingelöst' },
  'hunt.finish.grand.h3':{ en:'The €100 voucher has been claimed', de:'Der €100-Gutschein wurde bereits eingelöst' },
  'hunt.finish.grand.p': { en:"You still get 50% off on Mango Lassi — that's a great reward for finishing the hunt. Congratulations.", de:'Du bekommst trotzdem 50% Rabatt auf Mango Lassi — das ist eine tolle Belohnung. Herzlichen Glückwunsch.' },
  'hunt.finish.alert':   { en:'Show this screen at Indieflavours. Staff have been briefed. Take a screenshot as backup. Claimable only today', de:'Zeige diesen Bildschirm bei Indieflavours. Das Personal wurde informiert. Mach einen Screenshot. Nur heute einlösbar' },
  'hunt.finish.grand.pre':{ en:'First place: ', de:'Erster Platz: ' },
};
